version: "2.1"
services:
    hbase-standalone:
        # start shell: docker exec -it 7dbs_hbase-standalone_1 /opt/hbase-1.2.1/bin/hbase shell
        # https://github.com/hyness/hbase-rest-standalone
        # https://hub.docker.com/r/hyness/hbase-rest-standalone/
        image: hyness/hbase-rest-standalone:1.2.1
        volumes:
          - ./hbase/data:/data/hbase
          - ./hbase/zookeeper:/data/zookeeper
          - ./hbase/code:/code
        ports:
            - 2181:2181 # zookeeper
            - 8080:8080 # HBase Master API port
            - 16000:16000 # HBase Master port
            - 16010:16010 # HBase Master Web UI
            - 16020:16020 # Regionserver API port
            - 16030:16030 # HBase Regionserver web UI
    mongo:
        image: mongo:4.0.0-xenial
        # WARNING (Windows & OS X): this does not work for OSX, comment/delete next two lines
        volumes:
            - ./mongo/db:/data/db
            - ./mongo/code:/code
    mongo-express:
        image: mongo-express:0.49.0
        ports:
            - 8081:8081
